### PR TITLE
Error handle and validation 

### LINKED ISSUE #25: Show newest posts at top of page?
https://github.com/fac24/week2-alex-maria-peter-sonia/blob/de4b47cd1cdfa373333402d36fdf125bf57bc6bb/routes/showPosts.js#L12-L19

Might be nice for user if their post appears at the top of the page once posted?

### LINKED ISSUE #29: Error-handling
I just crashed your server (sorry!) I think by entering a username that was over 20 characters long. Whilst you do have a `.catch` handler in your POST route it is unfortunately only working for the ice cream insert, not the user one.

https://github.com/fac24/week2-alex-maria-peter-sonia/blob/15196139ff833296b117c16eba94036241f1917e/routes/home.js#L76-L83

You have two separate promises here, so both of them would need catches added. Right now if the first query rejects the server just crashes with an unhandled promise rejection.

_Chaining_ your promises would make this simpler and let you handle all errors in one place. It would also reduce the nesting you have. Remember you can return values from a `.then` to use them in the _next_ `.then` (this effectively creates a single promise at the end of the chain, which you can put a `.catch` on).

E.g. roughly:
```js
db.query("insert user")
  .then(result => result.rows[0]) // get the first row returned
  .then(user => user.id) // get the inserted user's id
  .then(id => db.query("insert ice cream", [id])) // user id to link ice cream to user
  .catch(error => ...) // handle any rejections from any promise in the chain
```

### LINKED ISSUE #30: Validation
In #29 I crashed the server by submitting a username over 20 characters long. If you're going to have restrictions on DB columns you should probably validate that your data meets those restrictions before inserting it (or handle the error and tell the user they need to use fewer characters). You probably at least want a `maxlength` on the input.

There probably isn't any reason to use anything but `TEXT` for string columns nowadays, unless you have a good reason for something to be limited in characters. Modern DBs can support huge strings 😅

### PR DESCRIPTION
**Pull request by mariaalouisaa**
Pretty sure this PR solves the error handling and validation issues.
- I wrapped db.query that submits the form inside `  if (request.body.username.length <= 20) {}` so that the server doenst break now on an input too large.
- I also added a "(max 20 chars)" note for the user so they know, though I feel there should be another step after the if statement to send the user a more obvious prompt 🤔
- I also got rid of some old code that we had comment out that we dont need just to tidy up.
- I changed the `postsHTML += ` to use the concat method so the new posts appear on the top of the list.

closes #30
closes #29
closes #25

### CODE REVIEW

File: routes/home.js [hunk 1]
```diff
@@ -58,51 +58,39 @@ function get(request, response) {
...
-      )
-      .then(() => {
-        response.redirect("/show-posts");
-      })
-      .catch((err) => {
-        response.status(500).send("<h1>Oops, something went wrong.</h1>");
-      });
-  });
+  //stop the user from breaking the server if username is too long
+  if (request.body.username.length <= 20) {
```
Comment (sonianb) [inline routes/home.js:69]: We could also add that directly to the DB by changing the `username VARCHAR(20)` to `username VARCHAR(250)` for example. But that looks good as well :)

Comment (lascellesabercrombie) [reply routes/home.js:69]: I think just increasing the count would make it vulnerable to the same attack by more determined typers. I think Oli suggested we could replace VARCHAR(250) with TEXT. But, as Sonia says, this looks like a good measure.

**Comment by lascellesabercrombie** [comment]
Looks great! Will merge now.
